name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: My_Hook
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_4Vt6wbGAO76vIUMuTDozd9tP5Vo8/MzKm7kVEO0