name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: My_Hook
        run: |
          curl -X POST ${{secrets.MY_SECRET_KEY}}
